### ISSUE TITLE
introduce `on-deprecate`

### ISSUE THREAD

**Issue by aconrad** [SurveyMonkey/defrost#5]
I would like to let the user have more fine-grained control over the behavior of defrost. Here I'm introducing a new keyword `on-deprecate` which would take either `error`, `warn` or `ignore` as a value.

```yaml
---
requirements:
- requirement: foo==2.0
  reason: please upgrade!
  on-deprecate: error|warn
```

The default value would be `error` if `on-deprecate` is not present.

* `error`: exit code 1 if package doesn't meet requirement
* `warn`: exit code 0 if package doesn't meet requirement (unless another package doesn't meet its requirement and is set to `on-deprecate: error`)

It would also be appropriate to introduce the command line option `-z` or `--zero` to force the exit code to be 0 regardless of the `on-deprecate` value.

@sudarkoff @msabramo
